export default {
    zrobiłem: ['zrobiłem', 'zrobiłam', 'zrobiłom', 'zrobiliśmy'],
    szukałem: ['szukałem', 'szukałam', 'szukałom', 'szukaliśmy'],
    znalazłem: ['znalazłem', 'znalazłam', 'znalazłom', 'znaleźliśmy'],
    moje: ['moje', 'moje', 'moje', 'nasze'],
    wyraziłem: ['wyraziłem', 'wyraziłam', 'wyraziłom', 'wyraziliśmy'],
    kliknąłem: ['kliknąłem', 'kliknęłam', 'klinkęłom', 'kliknęliśmy'],
    odwiedzałeś: ['odwiedzałeś', 'odwiedzałaś', 'odwiedzałoś', 'odwiedzaliście'],
    wyraziłeś: ['wyraziłeś', 'wyraziłaś', 'wyraziłoś', 'wyraziliście'],
    jesteś: ['jesteś', 'jesteś', 'jesteś', 'jesteście'],
    twoich: ['twoich', 'twoich', 'twoich', 'waszych'],
    tobie: ['tobie', 'tobie', 'tobie', 'wam'],
    twojej: ['twojej', 'twojej', 'twojej', 'waszej'],
    odkliknąłeś: ['odkliknąłeś', 'odkliknęłaś', 'odklikęłoś', 'odkliknęliście'],
    otwórz: ['otwórz', 'otwórz', 'otwórz', 'otwórzcie'],
    widzisz: ['widzisz', 'widzisz', 'widzisz', 'widzicie'],
    widzę: ['widzę', 'widzę', 'widzę', 'widzimy'],
    widziałem: ['widziałem', 'widziałam', 'widziałom', 'widzieliśmy'],
} as { [key: string]: string[] };
